function dx = orig_dyn_t_plan_to_t_total(in1,udummy)
%ORIG_DYN_T_PLAN_TO_T_TOTAL
%    DX = ORIG_DYN_T_PLAN_TO_T_TOTAL(IN1,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    25-Oct-2022 15:53:45

cqi = in1(1,:);
dqi = in1(4,:);
kai = in1(5,:);
kvi = in1(6,:);
sqi = in1(2,:);
dx = [-dqi.*sqi;cqi.*dqi;dqi;-kai-kvi.*2.0;0.0;0.0];
