function dx = orig_dyn_zero_to_t_plan(in1,udummy)
%ORIG_DYN_ZERO_TO_T_PLAN
%    DX = ORIG_DYN_ZERO_TO_T_PLAN(IN1,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    25-Oct-2022 15:53:45

cqi = in1(1,:);
dqi = in1(4,:);
kai = in1(5,:);
sqi = in1(2,:);
dx = [-dqi.*sqi;cqi.*dqi;dqi;kai;0.0;0.0];
