mex kinova_controller.cpp ...
    robot_models.cpp ...
    rnea.cpp ...
    robust_controller.cpp ...
    CXXFLAGS='$CXXFLAGS -std=c++14 -O2'

mex kinova_controller_ALTHOFF.cpp ...
    robot_models.cpp ...
    rnea.cpp ...
    robust_controller.cpp ...
    CXXFLAGS='$CXXFLAGS -std=c++14 -O2'